### ISSUE TITLE
Code Doesn't Compile on Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by NolanGarrett** [rjhansen/nsrlsvr#8]
When building on this OS, you get the following regarding lambda functions:

make  all-recursive
make[1]: Entering directory `/root/rjhansen-nsrlsvr-88620ef'
Making all in src
make[2]: Entering directory `/root/rjhansen-nsrlsvr-88620ef/src'
  CXX      nsrlsvr-main.o
  CXX      nsrlsvr-handler.o
handler.cc: In function ‘auto {anonymous}::tokenize(std::string&&, char)’:
handler.cc:177:35: error: parameter declared ‘auto’
                          [&](auto x) { return x != character; });
                                   ^
handler.cc: In lambda function:
handler.cc:177:47: error: ‘x’ was not declared in this scope
                          [&](auto x) { return x != character; });
                                               ^
handler.cc: In function ‘auto {anonymous}::tokenize(std::string&&, char)’:
handler.cc:191:34: error: parameter declared ‘auto’
                         [&](auto x) { return x != character; });
                                  ^
handler.cc: In lambda function:
handler.cc:191:46: error: ‘x’ was not declared in this scope
                         [&](auto x) { return x != character; });
                                              ^
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__find_if(_RandomAccessIterator, _RandomAccessIterator, _Predicate, std::random_access_iterator_tag) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >; _Predicate = {anonymous}::tokenize(std::string&&, char)::__lambda0]’:
/usr/include/c++/4.8/bits/stl_algo.h:4465:41:   required from ‘_IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >; _Predicate = {anonymous}::tokenize(std::string&&, char)::__lambda0]’
handler.cc:177:64:   required from here
/usr/include/c++/4.8/bits/stl_algo.h:214:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda0) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:177:28: note: candidate is:
                          [&](auto x) { return x != character; });
                            ^
handler.cc:177:36: note: {anonymous}::tokenize(std::string&&, char)::__lambda0
                          [&](auto x) { return x != character; });
                                    ^
handler.cc:177:36: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h:218:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda0) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:177:28: note: candidate is:
                          [&](auto x) { return x != character; });
                            ^
handler.cc:177:36: note: {anonymous}::tokenize(std::string&&, char)::__lambda0
                          [&](auto x) { return x != character; });
                                    ^
handler.cc:177:36: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h:222:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda0) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:177:28: note: candidate is:
                          [&](auto x) { return x != character; });
                            ^
handler.cc:177:36: note: {anonymous}::tokenize(std::string&&, char)::__lambda0
                          [&](auto x) { return x != character; });
                                    ^
handler.cc:177:36: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h:226:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda0) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:177:28: note: candidate is:
                          [&](auto x) { return x != character; });
                            ^
handler.cc:177:36: note: {anonymous}::tokenize(std::string&&, char)::__lambda0
                          [&](auto x) { return x != character; });
                                    ^
handler.cc:177:36: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h:234:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda0) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:177:28: note: candidate is:
                          [&](auto x) { return x != character; });
                            ^
handler.cc:177:36: note: {anonymous}::tokenize(std::string&&, char)::__lambda0
                          [&](auto x) { return x != character; });
                                    ^
handler.cc:177:36: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h:238:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda0) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:177:28: note: candidate is:
                          [&](auto x) { return x != character; });
                            ^
handler.cc:177:36: note: {anonymous}::tokenize(std::string&&, char)::__lambda0
                          [&](auto x) { return x != character; });
                                    ^
handler.cc:177:36: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h:242:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda0) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:177:28: note: candidate is:
                          [&](auto x) { return x != character; });
                            ^
handler.cc:177:36: note: {anonymous}::tokenize(std::string&&, char)::__lambda0
                          [&](auto x) { return x != character; });
                                    ^
handler.cc:177:36: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__find_if(_RandomAccessIterator, _RandomAccessIterator, _Predicate, std::random_access_iterator_tag) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >; _Predicate = {anonymous}::tokenize(std::string&&, char)::__lambda1]’:
/usr/include/c++/4.8/bits/stl_algo.h:4465:41:   required from ‘_IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >; _Predicate = {anonymous}::tokenize(std::string&&, char)::__lambda1]’
handler.cc:191:63:   required from here
/usr/include/c++/4.8/bits/stl_algo.h:214:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda1) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:191:27: note: candidate is:
                         [&](auto x) { return x != character; });
                           ^
handler.cc:191:35: note: {anonymous}::tokenize(std::string&&, char)::__lambda1
                         [&](auto x) { return x != character; });
                                   ^
handler.cc:191:35: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h:218:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda1) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:191:27: note: candidate is:
                         [&](auto x) { return x != character; });
                           ^
handler.cc:191:35: note: {anonymous}::tokenize(std::string&&, char)::__lambda1
                         [&](auto x) { return x != character; });
                                   ^
handler.cc:191:35: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h:222:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda1) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:191:27: note: candidate is:
                         [&](auto x) { return x != character; });
                           ^
handler.cc:191:35: note: {anonymous}::tokenize(std::string&&, char)::__lambda1
                         [&](auto x) { return x != character; });
                                   ^
handler.cc:191:35: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h:226:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda1) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:191:27: note: candidate is:
                         [&](auto x) { return x != character; });
                           ^
handler.cc:191:35: note: {anonymous}::tokenize(std::string&&, char)::__lambda1
                         [&](auto x) { return x != character; });
                                   ^
handler.cc:191:35: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h:234:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda1) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:191:27: note: candidate is:
                         [&](auto x) { return x != character; });
                           ^
handler.cc:191:35: note: {anonymous}::tokenize(std::string&&, char)::__lambda1
                         [&](auto x) { return x != character; });
                                   ^
handler.cc:191:35: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h:238:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda1) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:191:27: note: candidate is:
                         [&](auto x) { return x != character; });
                           ^
handler.cc:191:35: note: {anonymous}::tokenize(std::string&&, char)::__lambda1
                         [&](auto x) { return x != character; });
                                   ^
handler.cc:191:35: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from handler.cc:19:
/usr/include/c++/4.8/bits/stl_algo.h:242:23: error: no match for call to ‘({anonymous}::tokenize(std::string&&, char)::__lambda1) (const char&)’
    if (__pred(*__first))
                       ^
handler.cc:191:27: note: candidate is:
                         [&](auto x) { return x != character; });
                           ^
handler.cc:191:35: note: {anonymous}::tokenize(std::string&&, char)::__lambda1
                         [&](auto x) { return x != character; });
                                   ^
handler.cc:191:35: note:   candidate expects 0 arguments, 1 provided
make[2]: *** [nsrlsvr-handler.o] Error 1
make[2]: Leaving directory `/root/rjhansen-nsrlsvr-88620ef/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/rjhansen-nsrlsvr-88620ef'
make: *** [all] Error 2

**Comment by rjhansen** [comment]
This is not a bug.  You're trying to compile C++14 code with a pre-C++14 version of GCC.  Try GCC 4.9 or later.
